const STATES = {
  LOGIN_SIGNUP: 'LOGIN_SIGNUP',
  LOGIN_CAPTCHA: 'LOGIN_CAPTCHA',
  SIGNUP_OTP: 'SIGNUP_OTP',
  CONFIRMATION: 'CONFIRMATION',
  LOGIN_PASS: 'LOGIN_PASS',
  FORGET_PASS: 'FORGET_PASS',
  NEW_PASS: 'NEW_PASS',
  USER_INFO: 'USER_INFO',
}

export default STATES
