ARG BASE
FROM ${BASE} as build

LABEL build="storybook"

WORKDIR /app

COPY . .

RUN yarn

RUN yarn build:storybook

FROM nginx:alpine
COPY --from=build /app/storybook-static/ /usr/share/nginx/html/

