export const PRIMARY_STATE = {
  CANCELED: -1,
  PENDING: 1,
  PREPARATION: 2,
  BIKER_IN_ROUTE: 9,
  FINISHED: 4,
  HAS_REVIEWED: 1001,
}

export const SECONDARY_STATE = {
  CANCELED: -1, // backend state => ERROR
  PRE_ORDER: 8,
  PENDING: 1,
  PREPARATION: 2,
  BIKER_TO_VENDOR: 13,
  BIKER_AT_VENDOR: 12,
  BIKER_IN_ROUTE: 9,
  MAYBE_ARRIVED: 3, // backend state => DELIVERED
  FINISHED: 4, // backend state => DELIVERED_BY_CUSTOMER
  DELAYED: 5, // support
  DELAYED_SENDING: 6, // fake message
  REVIEW: 7,
  MESSAGE: 10,
  DELTA_SETTLEMENT_BLOCK: 11,
  LOOKING_FOR_BIKER: 14,
  BIKER_NEED_FOR_CALL: 15,
  NEW_ORDER: 16,
  BIKER_REACHED_CUSTOMER: 17,
  ERROR: 18, // backend state => DEFAULT
  HAS_REVIEWED: 1001,
}

export const PRE_ORDER_STATE = {
  TODAY: 'TODAY',
  TOMORROW: 'TOMORROW',
  AFTER_TOMORROW: 'AFTER_TOMORROW',
  TOMORROW1DAY: 'TOMORROW +1 DAY',
}

export const SUBSCRIPTION_LINK = '/vms/vendor/rx/'

export const MQTT_CONNECTION_LINK = 'wss://br2.snappfood.ir:8183/mqtt'

export const DESKTOP_ENV = 'ev-desktop'

export const TRANSACTIONS = {
  status: {
    COMPLETED: 'COMPLETED',
    PENDING: 'PENDING',
    REJECTED: 'REJECTED',
  },
  types: {
    IPG: 'IPG',
    WALLET: 'WALLET',
  },
  ipgType: {
    online: 'online',
    IPG_AP_DEBIT: 'IPG_AP_DEBIT',
    IPG_SNAPP_CREDIT: 'IPG_SNAPP_CREDIT',
  },
  reasons: {
    EMPTY: '',
    REASON_1: 'CREDIT_FROM_WALLET_TO_CUSTOMER_CREDIT',
    REASON_2:
      'CREDIT_FROM_WALLET_TO_CUSTOMER_CREDIT_FOR_USING_CREDIT_FOR_ONLINE_ORDER',
    REASON_3: 'CREDIT_MANUAL_INCREASE_FOR_WALLET_SETTLEMEN',
  },
}

export const HEAD_STATES = {
  IPG_ONLINE: 'IPG_ONLINE',
  IPG_AP_DEBIT: 'IPG_AP_DEBIT',
  IPG_SNAPP_CREDIT: 'IPG_SNAPP_CREDIT',
  IPG: 'IPG',
  WALLET_WITHDRAW: 'WALLET_WITHDRAW',
  WALLET_DEPOSIT: 'WALLET_DEPOSIT',
  NOT_SET: 'NOT_SET',
}

export const REASON_STATES = {
  ORDER_LEFT_OVER: 'ORDER_LEFT_OVER',
  ORDER: 'ORDER',
  INCREASE_WALLET: 'INCREASE_WALLET',
  RETURN_TO_WALLET: 'RETURN_TO_WALLET',
  NOT_SET: 'NOT_SET',
}
