export enum SuperType {
  'SEARCH-VENDORS' = 0,
  RESTAURANT = 1,
  CAFFE = 2,
  CONFECTIONERY = 3,
  SUPERMARKET = 4,
  BAKERY = 5,
  GROCERY = 6,
  NUTS = 7,
  JUICE = 8,
  OTHERS = 9,
  PROTEIN = 11,
}
export const Cuisin = {
  IRANIAN: 'cuisineId-2',
  ITALIAN: 'cuisineId-3',
  PIZZA: 'cuisineId-4',
  SEAFOOD: 'cuisineId-5',
  SANDWICH: 'cuisineId-8',
  BURGER: 'cuisineId-9',
  GILAN: 'cuisineId-12',
  FRIED: 'cuisineId-15',
  INDIAN: 'cuisineId-20',
  STEAK: 'cuisineId-22',
  ARABIC: 'cuisineId-23',
  BREAKFAST: 'cuisineId-25',
}
