const EVENTS = {
  PUSH_CLICKED: 'PUSH_CLICKED',
  PUSH_RECEIVED: 'PUSH_RECEIVED',
  LOCATION_RECEIVED: 'LOCATION_RECEIVED',
  LOCATION_ERROR: 'LOCATION_ERROR',
  IMG_RECEIVED: 'IMG_RECEIVED',
  BACK_KEY_PRESSED: 'BACK_KEY_PRESSED',
  RESUME: 'RESUME',
  SMS_EVENT: 'SMS_EVENT',
  SHORT_LINK_RESOLVED: 'SHORT_LINK_RESOLVED',
  MESSAGE_OPENED: 'MESSAGE_OPENED',
  MESSAGE_RECEIVED: 'MESSAGE_RECEIVED',
  MESSAGES_RECEIVED: 'MESSAGES_RECEIVED',
  UNREAD_MESSAGES_COUNT: 'UNREAD_MESSAGES_COUNT',
}

export default EVENTS
